name: CI

on:
  push:
    branches: [main]

jobs:
  contracts:
    name: Contracts (Hardhat)
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd contracts
          npm install

      - name: Compile contracts
        run: |
          cd contracts
          npm run compile

      - name: Run tests
        run: |
          cd contracts
          npm test

  frontend:
    name: Frontend
    runs-on: self-hosted
    needs: contracts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          echo "${{ secrets.ZAMA_HELLO_WORLD }}" > .env
          npm run build