name: CI (PR)

on:
  pull_request:
    branches: [main]

jobs:
  contracts:
    name: Contracts (Hardhat)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd contracts
          npm install

      - name: Compile contracts
        run: |
          cd contracts
          npm run compile

      - name: Run tests
        run: |
          cd contracts
          npm test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: contracts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Run frontend tests
        run: |
          cd frontend
          npm run typecheck
